# languages.py
LANGUAGES = {
    'english': {
        'welcome': 'Welcome',
        'dashboard': 'Dashboard',
        'language': 'Language',
        'select_language': 'Select Language',
        'total_uploads': 'Total Uploads',
        'pests_detected': 'Pests Detected',
        'your_queries': 'Your Queries',
        'quick_actions': 'Quick Actions',
        'upload_detect': 'Upload & Detect',
        'upload_desc': 'Upload pest image for detection',
        'ask_question': 'Ask Question',
        'ask_desc': 'Submit query to experts',
        'home_page': 'Home Page',
        'home_desc': 'Return to main page',
        'signout_desc': 'Logout from account',
        'recent_detections': 'My Recent Detections',
        'upload_more': 'Upload More',
        'date_time': 'Date & Time',
        'image': 'Image',
        'pest_detected': 'Pest Detected',
        'confidence': 'Confidence',
        'actions': 'Actions',
        'no_image': 'No Image',
        'unknown': 'Unknown',
        'view': 'View',
        'showing_detections': 'Showing {showing} of {total} detections.',
        'no_detections': 'No Detections Yet',
        'no_detections_desc': 'You haven\'t uploaded any images for pest detection.',
        'upload_first': 'Upload Your First Image',
        'changing_language': 'Changing language',
        'confirm_delete': 'Are you sure you want to delete this detection?',
        'delete_error': 'Error deleting upload',
        'crop_advisor': 'Crop Advisor',
        'crop_advisor_desc': 'Get AI-powered crop recommendations',
        'enter_farm_details': 'Enter Farm Details',
        'temperature_label': 'Temperature (°C) *',
        'weather_label': 'Weather Condition *',
        'humidity_label': 'Humidity (%) *',
        'rainfall_label': 'Rainfall (mm)',
        'location_label': 'Location/Region *',
        'soil_type_label': 'Soil Type *',
        'ph_label': 'pH Level',
        'nutrition_label': 'Soil Nutrition Level',
        'nitrogen_label': 'Nitrogen (N) Level (kg/ha)',
        'phosphorous_label': 'Phosphorous (P) Level (kg/ha)',
        'potassium_label': 'Potassium (K) Level (kg/ha)',
        'generate_recommendation': 'Generate AI Recommendation with Charts',
        'required_fields': '* Required fields',
        'sunny': 'Sunny',
        'partly_cloudy': 'Partly Cloudy',
        'cloudy': 'Cloudy',
        'rainy': 'Rainy',
        'dry': 'Dry',
        'humid': 'Humid',
        'clay': 'Clay',
        'sandy': 'Sandy',
        'loamy': 'Loamy',
        'silt': 'Silt',
        'peaty': 'Peaty',
        'chalky': 'Chalky',
        'rocky': 'Rocky',
        'low': 'Low',
        'medium': 'Medium',
        'high': 'High',
        'very_high': 'Very High',
        'ai_recommendation': 'AI Recommendation',
        'analysis_complete': 'Analysis Complete',
        'based_on_params': 'Based on your input parameters',
        'tips_better_results': 'Tips for Better Results',
        'soil_testing': 'Consider soil testing for accurate nutrient levels',
        'weather_monitoring': 'Monitor weather forecasts for optimal planting time',
        'local_experts': 'Consult local agricultural experts for region-specific advice',
        'crop_rotation': 'Consider crop rotation for soil health',
        'print_report': 'Print Report',
        'save_result': 'Save Result',
        'what_you_get': 'What you\'ll get:',
        'suitable_crops': 'Suitable crop recommendations',
        'pest_info': 'Common pest information',
        'planting_season': 'Planting season guidance',
        'soil_improvement': 'Soil improvement tips',
        'yield_estimates': 'Expected yield estimates',
        'no_analysis_yet': 'No Analysis Yet',
        'fill_form_desc': 'Fill out the form with your farm details',
        'ai_powered_suggestions': 'AI-powered crop suggestions',
        'crop_suitability': 'Crop Suitability Score',
        'soil_nutrients': 'Soil Nutrient Distribution',
        'environmental_conditions': 'Environmental Conditions',
        'pest_risk': 'Pest Risk Analysis',
        'crop_success': 'Crop recommendation generated successfully!',
        'fill_all_fields': 'Please fill all required fields',
        'api_config_error': 'API configuration error. Please contact administrator.',
        'generate_error': 'Error generating recommendation: ',
        'my_queries': 'Your Queries',
        'contact_us': 'Contact Us',
        'submit_query': 'Submit Query',
        'view_all_queries': 'View All Queries',
        'phone_number': 'Phone Number',
        'email_address': 'Email Address',
        'office_address': 'Office Address',
        'working_hours': 'Working Hours',
        'connect_with_us': 'Connect With Us',
        'github': 'GitHub',
        'linkedin': 'LinkedIn',
        'twitter': 'Twitter',
        'facebook': 'Facebook',
        'instagram': 'Instagram',
        'full_name': 'Full Name',
        'enter_name': 'Enter your full name',
        'email': 'Email Address',
        'enter_email': 'Enter your email address',
        'your_message': 'Your Message',
        'query_placeholder': 'Describe your query in detail...',
        'characters': 'characters',
        'clear': 'Clear',
        'what_we_help': 'What We Can Help With',
        'help_pest': 'Pest identification and control',
        'help_crop': 'Crop disease diagnosis',
        'help_soil': 'Soil and fertilizer advice',
        'help_organic': 'Organic farming methods',
        'help_general': 'General agricultural queries',
        'query_history': 'Query History',
        'total_queries': 'Total',
        "pending": "Pending",
"resolved": "Resolved",
        'query_message': 'Query',
        'admin_response': 'Admin Response',
        'responded_on': 'Responded on',
        'send_reminder': 'Send Reminder',
        'remind': 'Remind',
        'view_details': 'Details',
        'showing_queries': 'Showing',
        'of_total': 'of',
        'queries': 'queries',
        'no_queries_yet': 'No Queries Yet',
        'no_queries_desc': 'You haven\'t submitted any queries yet. Use the form on the left to submit your first query.',
        'message_too_short': 'Please provide a more detailed message (at least 10 characters)',
        'invalid_email': 'Please enter a valid email address',
        'confirm_reminder': 'Send reminder to admin about this query?',
        'reminder_sent': 'Reminder sent successfully!',
        'reminder_failed': 'Failed to send reminder. Please try again.',
        'error_occurred': 'An error occurred. Please try again.',
        'detailed_view': 'Detailed view would open here',
        'delete_query': 'Delete Query',
        'delete': 'Delete',
        'confirm_delete_query': 'Are you sure you want to delete this query? This action cannot be undone.',
        'query_deleted': 'Query deleted successfully!',
        'delete_failed': 'Failed to delete query. Please try again.',
        'contact_title': 'Contact Us',
        'contact_subtitle': 'Get in touch with us for any inquiries or support',
        'send_message': 'Send us a Message',
        'phone_title': 'Phone Number',
        'email_title': 'Email Address',
        'address_title': 'Office Address',
        'hours_title': 'Working Hours',
        'weekdays': 'Monday - Friday',
        'saturday': 'Saturday',
        'connect_title': 'Connect With Us',
        'submit_button': 'Send Message',
        
        # About Us page translations
        'about_title': 'About Pest Detection System',
        'about_subtitle': 'Revolutionizing Agriculture Through AI-Powered Pest Detection and Crop Management',
        'our_mission': 'Our Mission',
        'mission_text': 'To empower farmers with cutting-edge technology that simplifies pest identification, provides actionable insights, and promotes sustainable farming practices. We aim to reduce crop losses, increase yields, and support the agricultural community through intelligent, accessible solutions.',
        'what_we_provide': 'What We Provide',
        'feature_1_title': 'Instant Pest Detection',
        'feature_1_desc': 'Upload images of affected crops and get instant identification of pests using our advanced AI algorithms. Get detailed information about detected pests, their lifecycle, and damage patterns.',
        'feature_2_title': 'Smart Crop Recommendation',
        'feature_2_desc': 'Our intelligent system analyzes soil conditions, climate data, and market trends to recommend the most suitable crops for your land. Maximize your yield with data-driven insights.',
        'feature_3_title': 'Treatment Solutions',
        'feature_3_desc': 'Receive customized treatment plans including organic and chemical solutions, application methods, and preventive measures. Our database includes both traditional and modern pest control techniques.',
        'feature_4_title': 'Expert Consultation',
        'feature_4_desc': 'Connect with agricultural experts for personalized advice. Submit queries and get responses from certified professionals with years of farming experience.',
        'feature_5_title': 'Analytics Dashboard',
        'feature_5_desc': 'Track your pest detection history, crop recommendations, and farm performance through comprehensive analytics. Make informed decisions based on historical data.',
        'feature_6_title': 'Multi-Language Support',
        'feature_6_desc': 'Multi-language results: Review your pest detection findings in English, Hindi, or Bengali for better understanding.',
        'how_we_help': 'How We Help Farmers',
        'benefit_1': 'Increase Crop Yield',
        'benefit_1_desc': 'Early pest detection prevents major crop damage',
        'benefit_2': 'Reduce Costs',
        'benefit_2_desc': 'Precise treatment reduces pesticide expenses',
        'benefit_3': 'Save Time',
        'benefit_3_desc': 'Instant identification eliminates guesswork',
        'benefit_4': 'Data-Driven Decisions',
        'benefit_4_desc': 'Make informed choices with AI insights',
        'our_technology': 'Our Technology',
        'tech_1_title': 'AI & Machine Learning',
        'tech_1_desc': 'Deep learning approach for pest image classification',
        'tech_2_title': 'Cloud Computing',
        'tech_2_desc': 'Scalable infrastructure for fast processing and large data storage',
        'tech_3_title': 'Mobile-First Design',
        'tech_3_desc': 'Accessible on smartphones for farmers in remote areas',
        'our_impact': 'Our Impact',
        'impact_1': 'Farmers Served',
        'impact_2': 'Detection Accuracy',
        'impact_3': 'Pest Types Identified',
        'impact_4': 'Support Available',
        'cta_title': 'Ready to Transform Your Farming Experience?',
        'cta_desc': 'Join thousands of farmers who have already improved their crop yield and reduced losses with our intelligent pest detection system.',
        'detect_pests_now': 'Detect Pests Now',
        'join_now': 'Join Now',
        'about_us_nav': 'About Us',
        
        # Footer translations
        'footer_contact': 'Contact Us',
        'footer_address': '123 Agriculture Street, Farming District, Rural City 45678',
        'footer_phone': '+1 (555) 123-4567',
        'footer_email': 'support@pestdetection.com',
        'footer_quick_links': 'Quick Links',
        'footer_about': 'About Pest Detection',
        'footer_about_text': 'We provide advanced AI-powered pest detection and crop recommendation services to help farmers protect their crops and maximize yield.',
        'footer_about_text2': 'Our system uses machine learning to identify pests and suggest appropriate solutions.',
        'footer_about_text3': 'Available 24/7 for agricultural support and guidance.',
        'footer_copyright': '© 2024 Pest Detection System. All rights reserved. | Designed for Agricultural Excellence',
           "hero_title": "WORRIED WITH VARIOUS PESTS?",
        "hero_subtitle": "Don't worry, we will help you out with fastest Pest Identification system ever!",
        "hero_btn_identify": "IDENTIFY PEST",
        "hero_btn_learn": "LEARN MORE",
         "pest_gallery_title": "Pest Gallery",

        # PREDICTION PAGE
        "predict_title": "IDENTIFY THE PEST AFFECTING YOUR PLANT",
        "predict_subtitle": "Upload an image of the pest or affected plant for detection.",
        "predict_button": "Predict Pest",
        "predict_tip": "Use clear, well-lit images for best results.",
        "predict_tip_strong": "Tip",
"preview": "Preview",
"remove": "Remove",
"tip": "Tip",
"processing": "Processing...",

# Alerts
"alert_select_image": "Please select an image first!",
"alert_size": "File size must be less than 5MB!",
"alert_type": "Please upload JPG, JPEG or PNG images only!",


  "nav_home": "Home",
        "nav_dashboard": "Dashboard",
        "nav_prediction": "Prediction",
        "nav_crop_advisor": "Crop Advisor",
        "nav_queries": "Your Queries",
        "nav_about": "About Us",
        "nav_login": "Login",
        "nav_register": "Register",
        "nav_logout": "Logout",
        'timeline': 'Timeline',
'detection_result': 'Detection Result',
'species_identified': 'Species Identified',
'details': 'Details',
'delete_record': 'Delete record',
'view_complete_history': 'View Complete History',

# Add these to your language dictionaries in language.py
'back_to_dashboard': 'Back to Dashboard',
'detection_logs': 'Detection Logs',
'history_subtitle': 'Full archive of your crop analysis records.',
'filter_all': 'All Records',
'filter_pests': 'Pests Detected',
'filter_recent': 'Last 30 Days',
'search_placeholder': 'Search result...',
'col_timestamp': 'TIMESTAMP',
'col_preview': 'SCAN PREVIEW',
'col_result': 'DETECTION RESULT',
'col_confidence': 'CONFIDENCE SCORE',
'col_management': 'MANAGEMENT',
'healthy_status': 'Healthy / Clear',
'confirm_delete': 'Are you sure you want to delete this record?',
'last_24_hours': 'Last 24 Hours',
        'last_7_days': 'Last 7 Days',
        'last_30_days': 'Last 30 Days',
        'all_time': 'All Records',
        'search_placeholder': 'Search by pest name...',
        'nav_pest_library': 'Pest Library',
'login_prompt_title': 'Login Required',
'login_prompt_message': 'Please login to access additional pest information and features.',
'login_button': 'Login Now',
'close_button': 'Close',
'soil_type_analysis': 'Soil Type Analysis',
    'recommended_crops': 'Recommended Crops',
    'potential_pests': 'Potential Pests',
    'suitability_score': 'Suitability Score',
    'recommended_crops_count': 'Recommended Crops',
    'rainfall': 'Rainfall',
    'temperature': 'Temperature',
    'suitability_percentage': 'Suitability %',
    'nutrient_distribution': 'Nutrient Distribution',
    'environmental_trends': 'Environmental Trends',
    'values': 'Values',
    'pest_risk_analysis': 'Pest Risk Analysis',
    'soil_composition': 'Soil Composition',
    'download_feature': 'Download feature coming soon!',
    'no_crop_data': 'No crop data available',
    'crops_list': 'Crops',
    'pests_list': 'Pests',
    'risk': 'risk',
    # PEST LIBRARY TRANSLATIONS
    'admin_pest_library': 'Pest Library Management',
    'admin_subtitle': 'Manage the complete pest database. Add new pests, edit existing ones, and control what appears in the public library. Predefined pests (from pest_library.py) cannot be edited or deleted.',
    'pest_library': 'Pest Library',
    'library_subtitle': 'Your comprehensive digital encyclopedia for identifying, understanding, and managing agricultural pests. Access detailed information, prevention strategies, and control methods for effective crop protection.',
    'add_new_pest': 'Add New Pest',
    'migrate_pests': 'Migrate from Uploads',
    'cleanup_database': 'Cleanup Database',
    'database_info': 'Database Information',
    'predefined': 'Predefined',
    'custom': 'Custom',
    'new_pests': 'New (Last 5 Days)',
    'note': 'Note',
    'predefined_warning': 'Predefined pests (from pest_library.py) are read-only and cannot be edited or deleted. Only custom pests (added via admin panel) can be modified.',
    'search_placeholder': 'Search pests by name, scientific name, or description...',
    'all_severity': 'All Severity Levels',
    'low_severity': 'Low Severity',
    'medium_severity': 'Medium Severity',
    'high_severity': 'High Severity',
    'very_high_severity': 'Very High Severity',
    'all_types': 'All Types',
    'predefined_only': 'Predefined Only',
    'custom_only': 'Custom Only',
    'total_pests': 'Total Pests',
    'high_severity': 'High Severity',
    'newly_added': 'Newly Added',
    'custom_pests': 'Custom Pests',
    'predefined_pests': 'Predefined Pests',
    'effects': 'Effects',
    'solutions': 'Solutions',
    'added': 'Added',
    'detected': 'Detected',
    'times': 'times',
    'selected': 'selected',
    'no_pests_found': 'No Pests Found',
    'empty_library': 'The pest library is currently empty.',
    'add_first_pest': 'Add Your First Pest',
    'about_pest_management': 'About Pest Management',
    'identification_tips': 'Identification Tips',
    'prevention_strategies': 'Prevention Strategies',
    'quick_actions': 'Quick Actions',
    'tip1': 'Look for characteristic damage patterns on leaves',
    'tip2': 'Observe pest behavior and feeding times',
    'tip3': 'Check underside of leaves for eggs or larvae',
    'tip4': 'Use magnifying glass for small pests',
    'tip5': 'Note seasonal patterns and weather conditions',
    'strategy1': 'Practice crop rotation regularly',
    'strategy2': 'Maintain proper field sanitation',
    'strategy3': 'Use resistant crop varieties',
    'strategy4': 'Implement biological controls',
    'strategy5': 'Monitor fields regularly',
    'action1': 'Isolate infected plants immediately',
    'action2': 'Apply organic treatments first',
    'action3': 'Document pest progression',
    'action4': 'Consult experts for severe infestations',
    'action5': 'Follow safety protocols with chemicals',
    'select_all': 'Select All (Custom pests only)',
    'migrate_confirm': 'This will migrate pests from uploads to the library. Continue?',
    'cleanup_confirm': 'This will clean up pest database. Continue?',
    'delete_selected': 'Delete Selected',
    'clear_selection': 'Clear Selection',
    'view': 'View',
    'edit': 'Edit',
    'delete': 'Delete',
    'view_details': 'View Details',
    },   


    'bangla': {
        'welcome': 'স্বাগতম',
        'dashboard': 'ড্যাশবোর্ড',
        'language': 'ভাষা',
        'sign_out': 'সাইন আউট',
        'select_language': 'ভাষা নির্বাচন করুন',
        'total_uploads': 'মোট আপলোড',
        'pests_detected': 'পোকা শনাক্ত',
        'your_queries': 'আপনার প্রশ্ন',
        'quick_actions': 'দ্রুত কার্যক্রম',
        'upload_detect': 'আপলোড ও শনাক্ত',
        'upload_desc': 'পোকার ছবি আপলোড করে শনাক্ত করুন',
        'ask_question': 'প্রশ্ন করুন',
        'ask_desc': 'বিশেষজ্ঞদের প্রশ্ন জমা দিন',
        'home_page': 'হোম পেজ',
        'home_desc': 'প্রধান পৃষ্ঠায় ফিরে যান',
        'sign_out': 'সাইন আউট',
        'signout_desc': 'অ্যাকাউন্ট থেকে লগআউট',
        'recent_detections': 'আমার সাম্প্রতিক শনাক্তকরণ',
        'upload_more': 'আরও আপলোড',
        'date_time': 'তারিখ ও সময়',
        'image': 'ছবি',
        'pest_detected': 'পোকা শনাক্ত',
        'confidence': 'আত্মবিশ্বাস',
        'actions': 'ক্রিয়া',
        'no_image': 'ছবি নেই',
        'unknown': 'অজানা',
        'view': 'দেখুন',
        'showing_detections': '{total} টি শনাক্তকরণের মধ্যে {showing} টি দেখানো হচ্ছে',
        'no_detections': 'এখনও কোন শনাক্তকরণ নেই',
        'no_detections_desc': 'আপনি এখনও পোকা শনাক্তকরণের জন্য কোন ছবি আপলোড করেননি',
        'upload_first': 'আপনার প্রথম ছবি আপলোড করুন',
        'changing_language': 'ভাষা পরিবর্তন করা হচ্ছে',
        'confirm_delete': 'আপনি কি নিশ্চিত যে আপনি এই শনাক্তকরণটি মুছে ফেলতে চান?',
        'delete_error': 'আপলোড মুছতে ত্রুটি',
        'crop_advisor': 'ফসল উপদেষ্টা',
        'crop_advisor_desc': 'এআই-চালিত ফসল সুপারিশ পান',
        'enter_farm_details': 'খামারের বিবরণ লিখুন',
        'temperature_label': 'তাপমাত্রা (°C) *',
        'weather_label': 'আবহাওয়ার অবস্থা *',
        'humidity_label': 'আর্দ্রতা (%) *',
        'rainfall_label': 'বৃষ্টিপাত (মিমি)',
        'location_label': 'অবস্থান/অঞ্চল *',
        'soil_type_label': 'মাটির ধরন *',
        'ph_label': 'পিএইচ মাত্রা',
        'nutrition_label': 'মাটির পুষ্টি স্তর',
        'nitrogen_label': 'নাইট্রোজেন (N) মাত্রা (কেজি/হেক্টর)',
        'phosphorous_label': 'ফসফরাস (P) মাত্রা (কেজি/হেক্টর)',
        'potassium_label': 'পটাসিয়াম (K) মাত্রা (কেজি/হেক্টর)',
        'generate_recommendation': 'চার্ট সহ এআই সুপারিশ তৈরি করুন',
        'required_fields': '* প্রয়োজনীয় ক্ষেত্র',
        'sunny': 'সূর্যালোকিত',
        'partly_cloudy': 'আংশিক মেঘলা',
        'cloudy': 'মেঘলা',
        'rainy': 'বর্ষণ',
        'dry': 'শুষ্ক',
        'humid': 'আর্দ্র',
        'clay': 'কাদামাটি',
        'sandy': 'বালুকাময়',
        'loamy': 'দোআঁশ',
        'silt': 'পলি',
        'peaty': 'পিট',
        'chalky': 'চকচকে',
        'rocky': 'পাথুরে',
        'low': 'নিম্ন',
        'medium': 'মধ্যম',
        'high': 'উচ্চ',
        'very_high': 'অত্যন্ত উচ্চ',
        'ai_recommendation': 'এআই সুপারিশ',
        'analysis_complete': 'বিশ্লেষণ সম্পূর্ণ',
        'based_on_params': 'আপনার ইনপুট প্যারামিটার ভিত্তিক',
        'tips_better_results': 'ভাল ফলাফলের জন্য টিপস',
        'soil_testing': 'সঠিক পুষ্টি স্তরের জন্য মাটি পরীক্ষা বিবেচনা করুন',
        'weather_monitoring': 'সর্বোত্তম রোপণের সময়ের জন্য আবহাওয়ার পূর্বাভাস পর্যবেক্ষণ করুন',
        'local_experts': 'অঞ্চল-নির্দিষ্ট পরামর্শের জন্য স্থানীয় কৃষি বিশেষজ্ঞদের সাথে পরামর্শ করুন',
        'crop_rotation': 'মাটির স্বাস্থ্যের জন্য ফসলের আবর্তন বিবেচনা করুন',
        'print_report': 'রিপোর্ট প্রিন্ট করুন',
        'save_result': 'ফলাফল সংরক্ষণ করুন',
        'what_you_get': 'আপনি যা পাবেন:',
        'suitable_crops': 'উপযুক্ত ফসলের সুপারিশ',
        'pest_info': 'সাধারণ পোকামাকড়ের তথ্য',
        'planting_season': 'রোপণের মৌসুম নির্দেশিকা',
        'soil_improvement': 'মাটির উন্নয়নের টিপস',
        'yield_estimates': 'প্রত্যাশিত ফলনের অনুমান',
        'no_analysis_yet': 'এখনও কোন বিশ্লেষণ নেই',
        'fill_form_desc': 'আপনার খামারের বিবরণ দিয়ে ফর্মটি পূরণ করুন',
        'ai_powered_suggestions': 'এআই-চালিত ফসলের পরামর্শ',
        'crop_suitability': 'ফসল উপযোগিতা স্কোর',
        'soil_nutrients': 'মাটির পুষ্টি বণ্টন',
        'environmental_conditions': 'পরিবেশগত অবস্থা',
        'pest_risk': 'পোকামাকড় ঝুঁকি বিশ্লেষণ',
        'crop_success': 'ফসল সুপারিশ সফলভাবে তৈরি হয়েছে!',
        'fill_all_fields': 'সমস্ত প্রয়োজনীয় ক্ষেত্র পূরণ করুন',
        'api_config_error': 'এপিআই কনফিগারেশন ত্রুটি। দয়া করে প্রশাসকের সাথে যোগাযোগ করুন।',
        'generate_error': 'সুপারিশ তৈরি করতে ত্রুটি: ',
        'my_queries': 'আপনার প্রশ্ন',
        'contact_us': 'যোগাযোগ করুন',
        'submit_query': 'প্রশ্ন জমা দিন',
        'view_all_queries': 'সমস্ত প্রশ্ন দেখুন',
        'phone_number': 'ফোন নম্বর',
        'email_address': 'ইমেল ঠিকানা',
        'office_address': 'অফিসের ঠিকানা',
        'working_hours': 'কাজের সময়',
        'connect_with_us': 'আমাদের সাথে যুক্ত হন',
        'github': 'গিটহাব',
        'linkedin': 'লিঙ্কডইন',
        'twitter': 'টুইটার',
        'facebook': 'ফেসবুক',
        'instagram': 'ইনস্টাগ্রাম',
        'full_name': 'পুরো নাম',
        'enter_name': 'আপনার পুরো নাম লিখুন',
        'email': 'ইমেল ঠিকানা',
        'enter_email': 'আপনার ইমেল ঠিকানা লিখুন',
        'your_message': 'আপনার বার্তা',
        'query_placeholder': 'আপনার প্রশ্ন বিস্তারিত বর্ণনা করুন...',
        'characters': 'অক্ষর',
        'clear': 'পরিষ্কার করুন',
        'what_we_help': 'আমরা কী সাহায্য করতে পারি',
        'help_pest': 'পোকামাকড় সনাক্তকরণ এবং নিয়ন্ত্রণ',
        'help_crop': 'ফসল রোগ নির্ণয়',
        'help_soil': 'মাটি এবং সার পরামর্শ',
        'help_organic': 'জৈব কৃষি পদ্ধতি',
        'help_general': 'সাধারণ কৃষি প্রশ্ন',
        'query_history': 'প্রশ্ন ইতিহাস',
        'total_queries': 'মোট',
        'query_message': 'প্রশ্ন',
        "pending": "অপেক্ষমাণ",
"resolved": "সমাধান হয়েছে",
        'admin_response': 'প্রশাসনিক প্রতিক্রিয়া',
        'responded_on': 'উত্তর দেওয়া হয়েছে',
        'send_reminder': 'রিমাইন্ডার পাঠান',
        'remind': 'মনে করিয়ে দিন',
        'view_details': 'বিস্তারিত দেখুন',
        'showing_queries': 'দেখাচ্ছেন',
        'of_total': 'এর',
        'queries': 'প্রশ্ন',
        'no_queries_yet': 'এখনও কোন প্রশ্ন নেই',
        'no_queries_desc': 'আপনি এখনও কোন প্রশ্ন জমা দেননি। আপনার প্রথম প্রশ্ন জমা দিতে বাম দিকের ফর্মটি ব্যবহার করুন।',
        'message_too_short': 'দয়া করে আরও বিস্তারিত বার্তা প্রদান করুন (অন্তত 10 অক্ষর)',
        'invalid_email': 'দয়া করে একটি বৈধ ইমেল ঠিকানা লিখুন',
        'confirm_reminder': 'এই প্রশ্নটি সম্পর্কে অ্যাডমিনকে রিমাইন্ডার পাঠাতে চান?',
        'reminder_sent': 'রিমাইন্ডার সফলভাবে পাঠানো হয়েছে!',
        'reminder_failed': 'রিমাইন্ডার পাঠাতে ব্যর্থ হয়েছে। দয়া করে আবার চেষ্টা করুন।',
        'error_occurred': 'একটি ত্রুটি ঘটেছে। দয়া করে আবার চেষ্টা করুন।',
        'detailed_view': 'বিস্তারিত দৃশ্য এখানে খুলবে',
        'delete_query': 'প্রশ্ন মুছুন',
        'delete': 'মুছুন',
        'confirm_delete_query': 'আপনি কি নিশ্চিত যে আপনি এই প্রশ্নটি মুছতে চান? এই ক্রিয়াটি পূর্বাবস্থায় ফেরানো যাবে না।',
        'query_deleted': 'প্রশ্ন সফলভাবে মুছে ফেলা হয়েছে!',
        'delete_failed': 'প্রশ্ন মুছতে ব্যর্থ। দয়া করে আবার চেষ্টা করুন।',
        'contact_title': 'যোগাযোগ করুন',
        'contact_subtitle': 'যেকোনো জিজ্ঞাসা বা সাহায্যের জন্য আমাদের সাথে যোগাযোগ করুন',
        'send_message': 'আমাদের একটি বার্তা পাঠান',
        'phone_title': 'ফোন নম্বর',
        'email_title': 'ইমেইল ঠিকানা',
        'address_title': 'অফিসের ঠিকানা',
        'hours_title': 'কাজের সময়',
        'weekdays': 'সোমবার - শুক্রবার',
        'saturday': 'শনিবার',
        'connect_title': 'আমাদের সাথে যুক্ত হন',
        'submit_button': 'বার্তা পাঠান',
        "pest_gallery_title": "পোকামাকড় গ্যালারি",
        # About Us page translations in Bangla
        'about_title': 'পেস্ট ডিটেকশন সিস্টেম সম্পর্কে',
        'about_subtitle': 'এআই-চালিত পোকা শনাক্তকরণ এবং ফসল ব্যবস্থাপনা মাধ্যমে কৃষি বিপ্লব',
        'our_mission': 'আমাদের মিশন',
        'mission_text': 'কৃষকদের অত্যাধুনিক প্রযুক্তি দিয়ে ক্ষমতায়ন করতে যা পোকা শনাক্তকরণ সহজ করে, কার্যকরী অন্তর্দৃষ্টি প্রদান করে এবং টেকসই কৃষি অনুশীলনকে উন্নীত করে। আমরা বুদ্ধিমান, অ্যাক্সেসযোগ্য সমাধানের মাধ্যমে ফসলের ক্ষতি কমাতে, ফলন বাড়াতে এবং কৃষি সম্প্রদায়কে সমর্থন করতে চাই।',
        'what_we_provide': 'আমরা যা প্রদান করি',
        'feature_1_title': 'তাত্ক্ষণিক পোকা শনাক্তকরণ',
        'feature_1_desc': 'আক্রান্ত ফসলের ছবি আপলোড করুন এবং আমাদের উন্নত এআই অ্যালগরিদম ব্যবহার করে পোকার তাত্ক্ষণিক শনাক্তকরণ পান। শনাক্তকৃত পোকামাকড়, তাদের জীবনচক্র এবং ক্ষতির ধরণ সম্পর্কে বিস্তারিত তথ্য পান।',
        'feature_2_title': 'স্মার্ট ফসল সুপারিশ',
        'feature_2_desc': 'আমাদের বুদ্ধিমান সিস্টেম মাটির অবস্থা, জলবায়ু তথ্য এবং বাজার প্রবণতা বিশ্লেষণ করে আপনার জমির জন্য সবচেয়ে উপযুক্ত ফসল সুপারিশ করে। ডেটা-চালিত অন্তর্দৃষ্টি সহ আপনার ফলন সর্বাধিক করুন।',
        'feature_3_title': 'চিকিত্সা সমাধান',
        'feature_3_desc': 'জৈব এবং রাসায়নিক সমাধান, প্রয়োগ পদ্ধতি এবং প্রতিরোধমূলক ব্যবস্থা সহ কাস্টমাইজড চিকিত্সা পরিকল্পনা পান। আমাদের ডাটাবেসে ঐতিহ্যগত এবং আধুনিক উভয় পোকা নিয়ন্ত্রণ কৌশল রয়েছে।',
        'feature_4_title': 'বিশেষজ্ঞ পরামর্শ',
        'feature_4_desc': 'ব্যক্তিগতকৃত পরামর্শের জন্য কৃষি বিশেষজ্ঞদের সাথে সংযুক্ত হন। সার্টিফাইড পেশাদারদের কাছে প্রশ্ন জমা দিন এবং কয়েক বছরের কৃষি অভিজ্ঞতা সহ উত্তর পান।',
        'feature_5_title': 'বিশ্লেষণ ড্যাশবোর্ড',
        'feature_5_desc': 'বিস্তারিত বিশ্লেষণের মাধ্যমে আপনার পোকা শনাক্তকরণ ইতিহাস, ফসল সুপারিশ এবং খামারের কর্মক্ষমতা ট্র্যাক করুন। ঐতিহাসিক তথ্যের ভিত্তিতে সচেতন সিদ্ধান্ত নিন।',
        'feature_6_title': 'বহুভাষা সমর্থন',
        'feature_6_desc': 'ইংরেজি, হিন্দি, বাংলা এবং আরও আঞ্চলিক ভাষায় আমাদের প্ল্যাটফর্ম অ্যাক্সেস করুন। ভাষার বাধা নির্বিশেষে সমস্ত কৃষকের কাছে প্রযুক্তি অ্যাক্সেসযোগ্য করা আমাদের বিশ্বাস।',
        'how_we_help': 'আমরা কীভাবে কৃষকদের সাহায্য করি',
        'benefit_1': 'ফসল ফলন বৃদ্ধি',
        'benefit_1_desc': 'প্রাথমিক পোকা শনাক্তকরণ বড় ফসল ক্ষতি প্রতিরোধ করে',
        'benefit_2': 'খরচ কমান',
        'benefit_2_desc': 'সুনির্দিষ্ট চিকিত্সা কীটনাশক ব্যয় হ্রাস করে',
        'benefit_3': 'সময় বাঁচান',
        'benefit_3_desc': 'তাত্ক্ষণিক শনাক্তকরণ অনুমান দূর করে',
        'benefit_4': 'ডেটা-চালিত সিদ্ধান্ত',
        'benefit_4_desc': 'এআই অন্তর্দৃষ্টি দিয়ে সচেতন পছন্দ করুন',
        'our_technology': 'আমাদের প্রযুক্তি',
        'tech_1_title': 'এআই এবং মেশিন লার্নিং',
        'tech_1_desc': 'পোকামাকড়ের চিত্র শ্রেণিবিন্যাসে ডিপ লার্নিং পদ্ধতির প্রয়োগ',
        'tech_2_title': 'ক্লাউড কম্পিউটিং',
        'tech_2_desc': 'দ্রুত প্রক্রিয়াকরণ এবং বড় ডেটা স্টোরেজের জন্য স্কেলযোগ্য অবকাঠামো',
        'tech_3_title': 'মোবাইল-ফার্স্ট ডিজাইন',
        'tech_3_desc': 'দূরবর্তী এলাকার কৃষকদের জন্য স্মার্টফোনে অ্যাক্সেসযোগ্য',
        'our_impact': 'আমাদের প্রভাব',
        'impact_1': 'কৃষকদের সেবা',
        'impact_2': 'শনাক্তকরণ নির্ভুলতা',
        'impact_3': 'পোকা প্রকার শনাক্ত',
        'impact_4': 'সাপোর্ট উপলব্ধ',
        'cta_title': 'আপনার কৃষি অভিজ্ঞতা রূপান্তর করতে প্রস্তুত?',
        'cta_desc': 'হাজার হাজার কৃষকের সাথে যোগ দিন যারা ইতিমধ্যে আমাদের বুদ্ধিমান পোকা শনাক্তকরণ সিস্টেমের মাধ্যমে তাদের ফসল ফলন উন্নত করেছে এবং ক্ষতি কমিয়েছে।',
        'detect_pests_now': 'এখনই পোকা শনাক্ত করুন',
        'join_now': 'এখনই যোগ দিন',
        'about_us_nav': 'আমাদের সম্পর্কে',
        
        # Footer translations in Bangla
        'footer_contact': 'যোগাযোগ করুন',
        'footer_address': '১২৩ এগ্রিকালচার স্ট্রিট, ফার্মিং জেলা, রুরাল সিটি ৪৫৬৭৮',
        'footer_phone': '+১ (৫৫৫) ১২৩-৪৫৬৭',
        'footer_email': 'সাপোর্ট@পেস্টডিটেকশন.কম',
        'footer_quick_links': 'দ্রুত লিঙ্ক',
        'footer_about': 'পেস্ট ডিটেকশন সম্পর্কে',
        'footer_about_text': 'আমরা উন্নত এআই-চালিত পোকা শনাক্তকরণ এবং ফসল সুপারিশ পরিষেবা প্রদান করি যা কৃষকদের তাদের ফসল রক্ষা করতে এবং ফলন সর্বাধিক করতে সাহায্য করে।',
        'footer_about_text2': 'আমাদের সিস্টেম মেশিন লার্নিং ব্যবহার করে পোকামাকড় সনাক্ত করে এবং উপযুক্ত সমাধান প্রস্তাব করে।',
        'footer_about_text3': 'কৃষি সমর্থন এবং নির্দেশনার জন্য ২৪/৭ উপলব্ধ।',
        'footer_copyright': '© ২০২৪ পেস্ট ডিটেকশন সিস্টেম। সর্বস্বত্ব সংরক্ষিত। | কৃষি শ্রেষ্ঠত্বের জন্য ডিজাইন করা হয়েছে',
         "hero_title": "বিভিন্ন পোকামাকড় নিয়ে চিন্তিত?",
        "hero_subtitle": "চিন্তা করবেন না, আমরা সবচেয়ে দ্রুত পোকা শনাক্তকরণ সিস্টেম প্রদান করি!",
        "hero_btn_identify": "পোকা শনাক্ত করুন",
        "hero_btn_learn": "আরও জানুন",

        "predict_title": "আপনার গাছকে প্রভাবিত করা পোকা শনাক্ত করুন",
        "predict_subtitle": "পোকা বা আক্রান্ত গাছের ছবি আপলোড করুন।",
        "predict_button": "পোকা শনাক্ত করুন",
        "predict_tip": "ভাল ফলাফলের জন্য পরিষ্কার ও উজ্জ্বল ছবি ব্যবহার করুন।",
        "predict_tip_strong": "পরামর্শ",
          "preview": "পূর্বদৃশ্য",
        "remove": "মুছুন",
        "tip": "পরামর্শ",
        "processing": "প্রক্রিয়া চলছে...",

        # Alerts
        "alert_select_image": "দয়া করে প্রথমে একটি ছবি নির্বাচন করুন!",
        "alert_size": "ফাইলের আকার ৫MB এর কম হতে হবে!",
        "alert_type": "শুধুমাত্র JPG, JPEG অথবা PNG ছবি আপলোড করুন!",
         "nav_home": "হোম",
        "nav_dashboard": "ড্যাশবোর্ড",
        "nav_prediction": "পূর্বাভাস",
        "nav_crop_advisor": "ফসল পরামর্শ",
        "nav_queries": "আপনার প্রশ্ন",
        "nav_about": "আমাদের সম্পর্কে",
        "nav_login": "লগইন",
        "nav_register": "রেজিস্টার",
        "nav_logout": "লগআউট",
        'timeline': 'সময়রেখা',
'detection_result': 'শনাক্তকরণের ফলাফল',
'species_identified': 'শনাক্তকৃত প্রজাতি',
'details': 'বিস্তারিত',
'delete_record': 'রেকর্ড মুছুন',
'view_complete_history': 'সম্পূর্ণ ইতিহাস দেখুন',
'back_to_dashboard': 'ড্যাশবোর্ডে ফিরে যান',
'detection_logs': 'ডিটেকশন লগ',
'history_subtitle': 'আপনার ফসল বিশ্লেষণের রেকর্ডের সম্পূর্ণ আর্কাইভ।',
'filter_all': 'সমস্ত রেকর্ড',
'filter_pests': 'পোকামাকড় সনাক্ত হয়েছে',
'filter_recent': 'গত ৩০ দিন',
'search_placeholder': 'ফলাফল খুঁজুন...',
'col_timestamp': 'তারিখ ও সময়',
'col_preview': 'স্ক্যান প্রিভিউ',
'col_result': 'ডিটেকশন ফলাফল',
'col_confidence': 'নির্ভুলতা স্কোর',
'col_management': 'ব্যবস্থাপনা',
'healthy_status': 'সুস্থ / পরিষ্কার',
'confirm_delete': 'আপনি কি নিশ্চিতভাবে এই রেকর্ডটি মুছে ফেলতে চান?',
     'last_24_hours': 'শেষ ২৪ ঘণ্টা',
        'last_7_days': 'শেষ ৭ দিন',
        'last_30_days': 'শেষ ৩০ দিন',
        'all_time': 'সব রেকর্ড',
        'search_placeholder': 'পোকা নামে অনুসন্ধান করুন...',
        'nav_pest_library': 'পোকা লাইব্রেরি',
'login_prompt_title': 'লগইন প্রয়োজন',
'login_prompt_message': 'অতিরিক্ত পোস্ট তথ্য এবং বৈশিষ্ট্যগুলি অ্যাক্সেস করতে দয়া করে লগইন করুন।',
'login_button': 'এখনই লগইন করুন',
'close_button': 'বন্ধ করুন',
'soil_type_analysis': 'মাটির ধরন বিশ্লেষণ',
    'recommended_crops': 'প্রস্তাবিত ফসল',
    'potential_pests': 'সম্ভাব্য পোকামাকড়',
    'suitability_score': 'উপযোগিতা স্কোর',
    'recommended_crops_count': 'প্রস্তাবিত ফসল',
    'rainfall': 'বৃষ্টিপাত',
    'temperature': 'তাপমাত্রা',
    'suitability_percentage': 'উপযোগিতা %',
    'nutrient_distribution': 'পুষ্টি বণ্টন',
    'environmental_trends': 'পরিবেশগত প্রবণতা',
    'values': 'মান',
    'pest_risk_analysis': 'পোকামাকড় ঝুঁকি বিশ্লেষণ',
    'soil_composition': 'মাটির গঠন',
    'download_feature': 'ডাউনলোড বৈশিষ্ট্য শীঘ্রই আসছে!',
    'no_crop_data': 'কোন ফসল ডেটা পাওয়া যায়নি',
    'crops_list': 'ফসল',
    'risk': 'ঝুঁকি',
    'pests_list': 'পোকামাকড়',
    'admin_pest_library': 'পোকা লাইব্রেরি ব্যবস্থাপনা',
    'admin_subtitle': 'সম্পূর্ণ পোকা ডাটাবেস পরিচালনা করুন। নতুন পোকা যোগ করুন, বিদ্যমান পোকা সম্পাদনা করুন এবং নিয়ন্ত্রণ করুন কী প্রকাশ্যে লাইব্রেরিতে প্রদর্শিত হয়। পূর্বনির্ধারিত পোকা (pest_library.py থেকে) শুধুমাত্র পড়ার জন্য এবং সম্পাদনা বা মুছে ফেলা যাবে না।',
    'pest_library': 'পোকা লাইব্রেরি',
    'library_subtitle': 'কৃষি পোকা সনাক্তকরণ, বোঝা এবং পরিচালনার জন্য আপনার ব্যাপক ডিজিটাল এনসাইক্লোপিডিয়া। কার্যকর ফসল সুরক্ষার জন্য বিস্তারিত তথ্য, প্রতিরোধ কৌশল এবং নিয়ন্ত্রণ পদ্ধতিতে অ্যাক্সেস পান।',
    'add_new_pest': 'নতুন পোকা যোগ করুন',
    'migrate_pests': 'আপলোড থেকে স্থানান্তর করুন',
    'cleanup_database': 'ডাটাবেস পরিষ্কার করুন',
    'database_info': 'ডাটাবেস তথ্য',
    'predefined': 'পূর্বনির্ধারিত',
    'custom': 'কাস্টম',
    'new_pests': 'নতুন (গত 5 দিন)',
    'note': 'নোট',
    'predefined_warning': 'পূর্বনির্ধারিত পোকা (pest_library.py থেকে) শুধুমাত্র পড়ার জন্য এবং সম্পাদনা বা মুছে ফেলা যাবে না। শুধুমাত্র কাস্টম পোকা (অ্যাডমিন প্যানেলের মাধ্যমে যোগ করা) সংশোধন করা যাবে।',
    'search_placeholder': 'নাম, বৈজ্ঞানিক নাম বা বর্ণনা দ্বারা পোকা অনুসন্ধান করুন...',
    'all_severity': 'সব তীব্রতা স্তর',
    'low_severity': 'কম তীব্রতা',
    'medium_severity': 'মাঝারি তীব্রতা',
    'high_severity': 'উচ্চ তীব্রতা',
    'very_high_severity': 'খুব উচ্চ তীব্রতা',
    'all_types': 'সব ধরনের',
    'predefined_only': 'শুধুমাত্র পূর্বনির্ধারিত',
    'custom_only': 'শুধুমাত্র কাস্টম',
    'total_pests': 'মোট পোকা',
    'high_severity': 'উচ্চ তীব্রতা',
    'newly_added': 'নতুন যোগ করা',
    'custom_pests': 'কাস্টম পোকা',
    'predefined_pests': 'পূর্বনির্ধারিত পোকা',
    'effects': 'প্রভাব',
    'solutions': 'সমাধান',
    'added': 'যোগ করা হয়েছে',
    'detected': 'সনাক্ত করা হয়েছে',
    'times': 'বার',
    'selected': 'নির্বাচিত',
    'no_pests_found': 'কোন পোকা পাওয়া যায়নি',
    'empty_library': 'পোকা লাইব্রেরি বর্তমানে খালি।',
    'add_first_pest': 'আপনার প্রথম পোকা যোগ করুন',
    'about_pest_management': 'পোকা ব্যবস্থাপনা সম্পর্কে',
    'identification_tips': 'সনাক্তকরণ টিপস',
    'prevention_strategies': 'প্রতিরোধ কৌশল',
    'quick_actions': 'দ্রুত কর্ম',
    'tip1': 'পাতায় চরিত্রগত ক্ষতি প্যাটার্ন দেখুন',
    'tip2': 'পোকার আচরণ এবং খাওয়ার সময় লক্ষ্য করুন',
    'tip3': 'ডিম বা লার্ভার জন্য পাতার নীচে পরীক্ষা করুন',
    'tip4': 'ছোট পোকার জন্য বিবর্ধক কাচ ব্যবহার করুন',
    'tip5': 'মৌসুমী প্যাটার্ন এবং আবহাওয়া পরিস্থিতি নোট করুন',
    'strategy1': 'নিয়মিতভাবে ফসল ঘূর্ণন অনুশীলন করুন',
    'strategy2': 'সঠিক ক্ষেত্রের স্বাস্থ্যবিধি বজায় রাখুন',
    'strategy3': 'প্রতিরোধী ফসলের জাত ব্যবহার করুন',
    'strategy4': 'জৈবিক নিয়ন্ত্রণ প্রয়োগ করুন',
    'strategy5': 'ক্ষেত্র নিয়মিত পর্যবেক্ষণ করুন',
    'action1': 'আক্রান্ত গাছ অবিলম্বে আলাদা করুন',
    'action2': 'প্রথমে জৈব চিকিৎসা প্রয়োগ করুন',
    'action3': 'পোকার অগ্রগতি নথিভুক্ত করুন',
    'action4': 'গুরুতর সংক্রমণের জন্য বিশেষজ্ঞদের পরামর্শ নিন',
    'action5': 'রাসায়নিক দিয়ে নিরাপত্তা প্রোটোকল অনুসরণ করুন',
    'select_all': 'সব নির্বাচন করুন (শুধুমাত্র কাস্টম পোকা)',
    'migrate_confirm': 'এটি আপলোড থেকে পোকা লাইব্রেরিতে স্থানান্তর করবে। চালিয়ে যাবেন?',
    'cleanup_confirm': 'এটি পোকা ডাটাবেস পরিষ্কার করবে। চালিয়ে যাবেন?',
    'delete_selected': 'নির্বাচিত মুছুন',
    'clear_selection': 'নির্বাচন সাফ করুন',
    'view': 'দেখুন',
    'edit': 'সম্পাদনা করুন',
    'delete': 'মুছুন',
    'view_details': 'বিস্তারিত দেখুন',
    },

    'hindi': {
        'welcome': 'स्वागत है',
        'dashboard': 'डैशबोर्ड',
        'language': 'भाषा',
        'sign_out': 'साइन आउट',
        'select_language': 'भाषा चुनें',
        'total_uploads': 'कुल अपलोड',
        'pests_detected': 'कीट पाए गए',
        'your_queries': 'आपके प्रश्न',
        'quick_actions': 'त्वरित कार्रवाई',
        'upload_detect': 'अपलोड और पहचानें',
        'upload_desc': 'कीट छवि पहचान के लिए अपलोड करें',
        'ask_question': 'प्रश्न पूछें',
        'ask_desc': 'विशेषज्ञों को प्रश्न जमा करें',
        'home_page': 'होम पेज',
        'home_desc': 'मुख्य पृष्ठ पर वापस जाएं',
        'sign_out': 'साइन आउट',
        'signout_desc': 'खाते से लॉगआउट करें',
        'recent_detections': 'मेरी हालिया पहचान',
        'upload_more': 'और अपलोड करें',
        'date_time': 'तारीख और समय',
        'image': 'छवि',
        'pest_detected': 'कीट पहचाना गया',
        'confidence': 'आत्मविश्वास',
        'actions': 'क्रियाएं',
        'no_image': 'कोई छवि नहीं',
        'unknown': 'अज्ञात',
        'view': 'देखें',
        'showing_detections': '{total} पहचान में से {showing} दिखाया जा रहा है',
        'no_detections': 'अभी तक कोई पहचान नहीं',
        'no_detections_desc': 'आपने अभी तक कीट पहचान के लिए कोई छवि अपलोड नहीं की है',
        'upload_first': 'अपनी पहली छवि अपलोड करें',
        'changing_language': 'भाषा बदली जा रही है',
        'confirm_delete': 'क्या आप वाकई इस पहचान को हटाना चाहते हैं?',
        'delete_error': 'अपलोड हटाने में त्रुटि',
        'crop_advisor': 'फसल सलाहकार',
        'crop_advisor_desc': 'एआई-संचालित फसल अनुशंसाएं प्राप्त करें',
        'enter_farm_details': 'खेत का विवरण दर्ज करें',
        'temperature_label': 'तापमान (°C) *',
        'weather_label': 'मौसम की स्थिति *',
        'humidity_label': 'आर्द्रता (%) *',
        'rainfall_label': 'वर्षा (मिमी)',
        'location_label': 'स्थान/क्षेत्र *',
        'soil_type_label': 'मिट्टी का प्रकार *',
        'ph_label': 'पीएच स्तर',
        'nutrition_label': 'मिट्टी पोषण स्तर',
        'nitrogen_label': 'नाइट्रोजन (N) स्तर (किग्रा/हेक्टेयर)',
        'phosphorous_label': 'फास्फोरस (P) स्तर (किग्रा/हेक्टेयर)',
        'potassium_label': 'पोटेशियम (K) स्तर (किग्रा/हेक्टेयर)',
        'generate_recommendation': 'चार्ट के साथ एआई अनुशंसा उत्पन्न करें',
        'required_fields': '* आवश्यक फ़ील्ड',
        'sunny': 'धूप',
        'partly_cloudy': 'आंशिक बादल',
        'cloudy': 'बादल',
        'rainy': 'बारिश',
        'dry': 'शुष्क',
        'humid': 'आर्द्र',
        'clay': 'चिकनी मिट्टी',
        'sandy': 'रेतीली',
        'loamy': 'दोमट',
        'silt': 'गाद',
        'peaty': 'पीट',
        'chalky': 'चाकीली',
        'rocky': 'चट्टानी',
        'low': 'कम',
        'medium': 'मध्यम',
        'high': 'उच्च',
        'very_high': 'बहुत उच्च',
        'ai_recommendation': 'एआई अनुशंसा',
        'analysis_complete': 'विश्लेषण पूर्ण',
        'based_on_params': 'आपके इनपुट पैरामीटर के आधार पर',
        'tips_better_results': 'बेहतर परिणामों के लिए सुझाव',
        'soil_testing': 'सटीक पोषक तत्व स्तर के लिए मिट्टी परीक्षण पर विचार करें',
        'weather_monitoring': 'इष्टतम रोपण समय के लिए मौसम पूर्वानुमान की निगरानी करें',
        'local_experts': 'क्षेत्र-विशिष्ट सलाह के लिए स्थानीय कृषि विशेषज्ञों से परामर्श लें',
        'crop_rotation': 'मिट्टी के स्वास्थ्य के लिए फसल चक्रण पर विचार करें',
        'print_report': 'रिपोर्ट प्रिंट करें',
        'save_result': 'परिणाम सहेजें',
        'what_you_get': 'आपको क्या मिलेगा:',
        'suitable_crops': 'उपयुक्त फसल अनुशंसाएं',
        'pest_info': 'सामान्य कीट जानकारी',
        'planting_season': 'रोपण मौसम मार्गदर्शन',
        'soil_improvement': 'मिट्टी सुधार टिप्स',
        'yield_estimates': 'अपेक्षित उपज अनुमान',
        'no_analysis_yet': 'अभी तक कोई विश्लেষण नहीं',
        'fill_form_desc': 'अपने खेत के विवरण के साथ फॉर्म भरें',
        'ai_powered_suggestions': 'एआई-संचालित फसल सुझाव',
        'crop_suitability': 'फसल उपयुक्तता स्कोर',
        'soil_nutrients': 'मिट्टी पोषक तत्व वितरण',
        'environmental_conditions': 'पर्यावरणीय स्थितियाँ',
        'pest_risk': 'कीट जोखिम विश्लेषण',
        'crop_success': 'फसल अनुशंसा सफलतापूर्वक उत्पन्न हुई!',
        'fill_all_fields': 'कृपया सभी आवश्यक फ़ील्ड भरें',
        'api_config_error': 'एपीआई कॉन्फ़िगरेशन त्रुटि। कृपया व्यवस्थापक से संपर्क करें।',
        'generate_error': 'अनुशंसा उत्पन्न करने में त्रुटि: ',
        'my_queries': 'आपके प्रश्न',
        'contact_us': 'संपर्क करें',
        'submit_query': 'प्रश्न जमा करें',
        'view_all_queries': 'सभी प्रश्न देखें',
        'phone_number': 'फोन नंबर',
        'email_address': 'ईमेल पता',
        'office_address': 'कार्यालय का पता',
        'working_hours': 'कार्य घंटे',
        'connect_with_us': 'हमसे जुड़ें',
        'github': 'गिटहब',
        'linkedin': 'लिंक्डइन',
        'twitter': 'ट्विटर',
        'facebook': 'फेसबुक',
        'instagram': 'इंस्टाग्राम',
        'full_name': 'पूरा नाम',
        'enter_name': 'अपना पूरा नाम दर्ज करें',
        'email': 'ईमेल पता',
        'enter_email': 'अपना ईमेल पता दर्ज करें',
        'your_message': 'आपका संदेश',
        'query_placeholder': 'अपना प्रश्न विस्तार से वर्णन करें...',
        'characters': 'वर्ण',
        'clear': 'साफ़ करें',
        'what_we_help': 'हम किसमें मदद कर सकते हैं',
        'help_pest': 'कीट पहचान और नियंत्रण',
        'help_crop': 'फसल रोग निदान',
        'help_soil': 'मिट्टी और उर्वरक सलाह',
        'help_organic': 'जैविक खेती के तरीके',
        'help_general': 'सामान्य कृषि प्रश्न',
        'query_history': 'प्रश्न इतिहास',
        'total_queries': 'कुल',
        "pending": "लंबित",
"resolved": "सुलझाया गया",
        'query_message': 'प्रश्न',
        'admin_response': 'प्रशासनिक प्रतिक्रिया',
        'responded_on': 'उत्तर दिया गया',
        'send_reminder': 'अनुस्मारक भेजें',
        'remind': 'याद दिलाएं',
        'view_details': 'विवरण देखें',
        'showing_queries': 'दिखा रहे हैं',
        'of_total': 'का',
        'queries': 'प्रश्न',
        'no_queries_yet': 'अभी तक कोई प्रश्न नहीं',
        'no_queries_desc': 'आपने अभी तक कोई प्रश्न जमा नहीं किया है। अपना पहला प्रश्न जमा करने के लिए बाईं ओर फॉर्म का उपयोग करें।',
        'message_too_short': 'कृपया अधिक विस्तृत संदेश प्रदान करें (कम से कम 10 वर्ण)',
        'invalid_email': 'कृपया एक मान्य ईमेल पता दर्ज करें',
        'confirm_reminder': 'क्या इस प्रश्न के बारे में एडमिन को अनुस्मारक भेजना है?',
        'reminder_sent': 'अनुस्मारक सफलतापूर्वक भेजा गया!',
        'reminder_failed': 'अनुस्मारक भेजने में विफल। कृपया पुनः प्रयास करें।',
        'error_occurred': 'एक त्रुटि हुई। कृपया पुनः प्रयास करें।',
        'detailed_view': 'विस्तृत दृश्य यहां खुलेगा',
        'delete_query': 'प्रश्न हटाएं',
        'delete': 'हटाएं',
        'confirm_delete_query': 'क्या आप वाकई इस प्रश्न को हटाना चाहते हैं? इस क्रिया को पूर्ववत नहीं किया जा सकता।',
        'query_deleted': 'प्रश्न सफलतापूर्वक हटा दिया गया!',
        'delete_failed': 'प्रश्न हटाने में विफल। कृपया पुनः प्रयास करें।',
        'contact_title': 'संपर्क करें',
        'contact_subtitle': 'किसी भी पूछताछ या सहायता के लिए हमसे संपर्क करें',
        'send_message': 'हमें संदेश भेजें',
        'phone_title': 'फोन नंबर',
        'email_title': 'ईमेल पता',
        'address_title': 'कार्यालय का पता',
        'hours_title': 'कार्य घंटे',
        'weekdays': 'सोमवार - शुक्रवार',
        'saturday': 'शनिवार',
        'connect_title': 'हमसे जुड़ें',
        'submit_button': 'संदेश भेजें',
        
        # About Us page translations in Hindi
        'about_title': 'पेस्ट डिटेक्शन सिस्टम के बारे में',
        'about_subtitle': 'एआई-संचालित कीट पहचान और फसल प्रबंधन के माध्यम से कृषि में क्रांति',
        'our_mission': 'हमारा मिशन',
        'mission_text': 'किसानों को अत्याधुनिक तकनीक से सशक्त बनाना जो कीट पहचान को सरल बनाती है, कार्रवाई योग्य अंतर्दृष्टि प्रदान करती है और टिकाऊ कृषि प्रथाओं को बढ़ावा देती है। हम बुद्धिमान, सुलभ समाधानों के माध्यम से फसल के नुकसान को कम करने, उपज बढ़ाने और कृषि समुदाय का समर्थन करने का लक्ष्य रखते हैं।',
        'what_we_provide': 'हम क्या प्रदान करते हैं',
        'feature_1_title': 'तत्काल कीट पहचान',
        'feature_1_desc': 'प्रभावित फसलों की छवियां अपलोड करें और हमारे उन्नत एआई एल्गोरिदम का उपयोग करके कीटों की तत्काल पहचान प्राप्त करें। पाए गए कीटों, उनके जीवनचक्र और क्षति पैटर्न के बारे में विस्तृत जानकारी प्राप्त करें।',
        'feature_2_title': 'स्मार्ट फसल सिफारिश',
        'feature_2_desc': 'हमारी बुद्धिमान प्रणाली मिट्टी की स्थिति, जलवायु डेटा और बाजार के रुझानों का विश्लेषण करके आपकी भूमि के लिए सबसे उपयुक्त फसलों की सिफारिश करती है। डेटा-संचालित अंतर्दृष्टि के साथ अपनी उपज को अधिकतम करें।',
        'feature_3_title': 'उपचार समाधान',
        'feature_3_desc': 'कार्बनिक और रासायनिक समाधान, आवेदन विधियों और निवारक उपायों सहित अनुकूलित उपचार योजनाएं प्राप्त करें। हमारे डेटाबेस में पारंपरिक और आधुनिक दोनों कीट नियंत्रण तकनीकें शामिल हैं।',
        'feature_4_title': 'विशेषज्ञ परामर्श',
        'feature_4_desc': 'व्यक्तिगत सलाह के लिए कृषि विशेषज्ञों से जुड़ें। प्रमाणित पेशेवरों को प्रश्न जमा करें और वर्षों के कृषि अनुभव वाले उत्तर प्राप्त करें।',
        'feature_5_title': 'एनालिटिक्स डैशबोर्ड',
        'feature_5_desc': 'व्यापक एनालिटिक्स के माध्यम से अपनी कीट पहचान इतिहास, फसल सिफारिशों और खेत के प्रदर्शन को ट्रैक करें। ऐतिहासिक डेटा के आधार पर सूचित निर्णय लें।',
        'feature_6_title': 'बहुभाषा समर्थन',
        'feature_6_desc': 'अंग्रेजी, हिंदी, बंगाली और अधिक क्षेत्रीय भाषाओं में हमारे प्लेटफॉर्म तक पहुंचें। हम भाषा बाधाओं के बावजूद सभी किसानों के लिए प्रौद्योगिकी को सुलभ बनाने में विश्वास करते हैं।',
        'how_we_help': 'हम किसानों की कैसे मदद करते हैं',
        'benefit_1': 'फसल उपज बढ़ाएं',
        'benefit_1_desc': 'प्रारंभिक कीट पहचान प्रमुख फसल क्षति को रोकती है',
        'benefit_2': 'लागत कम करें',
        'benefit_2_desc': 'सटीक उपचार कीटनाशक व्यय को कम करता है',
        'benefit_3': 'समय बचाएं',
        'benefit_3_desc': 'तत्काल पहचान अटकलों को समाप्त करती है',
        'benefit_4': 'डेटा-संचालित निर्णय',
        'benefit_4_desc': 'एआई अंतर्दृष्टि के साथ सूचित विकल्प बनाएं',
        'our_technology': 'हमारी प्रौद्योगिकी',
        'tech_1_title': 'एआई और मशीन लर्निंग',
        'tech_1_desc': 'कीट छवि वर्गीकरण हेतु डीप लर्निंग दृष्टिकोण',
        'tech_2_title': 'क्लाउड कंप्यूटिंग',
        'tech_2_desc': 'तेज प्रसंस्करण और बड़े डेटा संग्रहण के लिए स्केलेबल बुनियादी ढांचा',
        'tech_3_title': 'मोबाइल-फर्स्ट डिजाइन',
        'tech_3_desc': 'दूरदराज के इलाकों में किसानों के लिए स्मार्टफोन पर सुलभ',
        'our_impact': 'हमारा प्रभाव',
        'impact_1': 'किसानों की सेवा',
        'impact_2': 'पहचान सटीकता',
        'impact_3': 'कीट प्रकारों की पहचान',
        'impact_4': 'समर्थन उपलब्ध',
        'cta_title': 'अपने कृषि अनुभव को बदलने के लिए तैयार हैं?',
        'cta_desc': 'हजारों किसानों से जुड़ें जिन्होंने पहले ही हमारी बुद्धिमान कीट पहचान प्रणाली के साथ अपनी फसल उपज में सुधार किया है और नुकसान कम किया है।',
        'detect_pests_now': 'अभी कीटों का पता लगाएं',
        'join_now': 'अभी जुड़ें',
        'about_us_nav': 'हमारे बारे में',
        "pest_gallery_title": "कीट गैलरी",
        
        # Footer translations in Hindi
        'footer_contact': 'संपर्क करें',
        'footer_address': '१२३ कृषि स्ट्रीट, कृषि जिला, ग्रामीण शहर ४५६७८',
        'footer_phone': '+१ (५५५) १२३-४५६७',
        'footer_email': 'सपोर्ट@पेस्टडिटेक्शन.कॉम',
        'footer_quick_links': 'त्वरित लिंक',
        'footer_about': 'पेस्ट डिटेक्शन के बारे में',
        'footer_about_text': 'हम उन्नत एआई-संचालित कीट पहचान और फसल सिफारिश सेवाएं प्रदान करते हैं जो किसानों को उनकी फसलों की रक्षा करने और उपज को अधिकतम करने में मदद करती हैं।',
        'footer_about_text2': 'हमारी प्रणाली मशीन लर्निंग का उपयोग करके कीटों की पहचान करती है और उचित समाधान सुझाती है।',
        'footer_about_text3': 'कृषि सहायता और मार्गदर्शन के लिए २४/७ उपलब्ध।',
        'footer_copyright': '© २०२४ पेस्ट डिटेक्शन सिस्टम। सर्वाधिकार सुरक्षित। | कृषि उत्कृष्टता के लिए डिज़ाइन किया गया',



         "hero_title": "क्या आपकी फसल कीटों से परेशान है?",
        "hero_subtitle": "चिंता न करें, हम आपको सबसे तेज़ कीट पहचान प्रणाली प्रदान करते हैं!",
        "hero_btn_identify": "कीट पहचानें",
        "hero_btn_learn": "और जानें",

        "predict_title": "आपके पौधे को प्रभावित करने वाले कीट की पहचान करें",
        "predict_subtitle": "कीट या प्रभावित पौधे की छवि अपलोड करें।",
        "predict_button": "कीट पहचानें",
        "predict_tip": "बेहतर परिणामों के लिए स्पष्ट और उजाले वाली तस्वीरें उपयोग करें।",
        "predict_tip_strong": "सुझाव",


        "preview": "पूर्वावलोकन",
"remove": "हटाएं",
"tip": "सुझाव",
"processing": "प्रक्रिया जारी है...",
"alert_select_image": "कृपया पहले एक छवि चुनें!",
"alert_size": "फ़ाइल आकार 5MB से कम होना चाहिए!",
"alert_type": "केवल JPG, JPEG या PNG छवियाँ अपलोड करें!",
  "nav_home": "होम",
        "nav_dashboard": "डैशबोर्ड",
        "nav_prediction": "पूर्वानुमान",
        "nav_crop_advisor": "फसल सलाहकार",
        "nav_queries": "आपकी क्वेरी",
        "nav_about": "हमारे बारे में",
        "nav_login": "लॉगिन",
        "nav_register": "रजिस्टर",
        "nav_logout": "लॉगआउट",
        'timeline': 'समयरेखा',
'detection_result': 'पहचान परिणाम',
'species_identified': 'पहचानी गई प्रजाति',
'details': 'विवरण',
'delete_record': 'रिकॉर्ड हटाएँ',
'view_complete_history': 'पूरा इतिहास देखें',

'back_to_dashboard': 'डैशबोर्ड पर वापस जाएं',
'detection_logs': 'डिटेक्शन लॉग्स',
'history_subtitle': 'आपके फसल विश्लेषण रिकॉर्ड का पूरा संग्रह।',
'filter_all': 'सभी रिकॉर्ड',
'filter_pests': 'कीट मिले',
'filter_recent': 'पिछले 30 दिन',
'search_placeholder': 'परिणाम खोजें...',
'col_timestamp': 'समय और दिनांक',
'col_preview': 'स्कैन पूर्वावलोकन',
'col_result': 'डिटेक्शन परिणाम',
'col_confidence': 'सटीकता स्कोर',
'col_management': 'प्रबंधन',
'healthy_status': 'स्वस्थ / साफ',
'confirm_delete': 'क्या आप वाकई इस रिकॉर्ड को हटाना चाहते हैं?',
 'last_24_hours': 'आखिरी 24 घंटे',
        'last_7_days': 'आखिरी 7 दिन',
        'last_30_days': 'आखिरी 30 दिन',
        'all_time': 'सभी रिकॉर्ड',
        'search_placeholder': 'कीट नाम से खोजें...',
        'nav_pest_library': 'पेस्ट लाइब्रेरी',
'login_prompt_title': 'लॉगिन आवश्यक',
'login_prompt_message': 'अतिरिक्त पेस्ट जानकारी और सुविधाओं तक पहुंचने के लिए कृपया लॉगिन करें।',
'login_button': 'अभी लॉगिन करें',
'close_button': 'बंद करें',
 'soil_type_analysis': 'मिट्टी का प्रकार विश्लेषण',
    'recommended_crops': 'सिफारिशित फसलें',
    'potential_pests': 'संभावित कीट',
    'suitability_score': 'उपयुक्तता स्कोर',
    'recommended_crops_count': 'सिफारिशित फसलें',
    'rainfall': 'वर्षा',
    'temperature': 'तापमान',
    'suitability_percentage': 'उपयुक्तता %',
    'nutrient_distribution': 'पोषक तत्व वितरण',
    'environmental_trends': 'पर्यावरणीय रुझान',
    'values': 'मान',
    'pest_risk_analysis': 'कीट जोखिम विश्लेषण',
    'soil_composition': 'मिट्टी संरचना',
    'download_feature': 'डाउनलोड सुविधा जल्द ही आ रही है!',
    'no_crop_data': 'कोई फसल डेटा उपलब्ध नहीं',
    'crops_list': 'फसलें',
    'risk': 'जोखिम',
    'pests_list': 'कीट',
    'admin_pest_library': 'कीट लाइब्रेरी प्रबंधन',
    'admin_subtitle': 'पूर्ण कीट डेटाबेस प्रबंधित करें। नए कीट जोड़ें, मौजूदा कीट संपादित करें और नियंत्रित करें कि सार्वजनिक लाइब्रेरी में क्या दिखाई देता है। पूर्वनिर्धारित कीट (pest_library.py से) केवल पढ़ने के लिए हैं और संपादित या हटाए नहीं जा सकते।',
    'pest_library': 'कीट लाइब्रेरी',
    'library_subtitle': 'कृषि कीटों की पहचान, समझ और प्रबंधन के लिए आपका व्यापक डिजिटल विश्वकोश। प्रभावी फसल संरक्षण के लिए विस्तृत जानकारी, रोकथाम रणनीतियों और नियंत्रण विधियों तक पहुंचें।',
    'add_new_pest': 'नया कीट जोड़ें',
    'migrate_pests': 'अपलोड से स्थानांतरित करें',
    'cleanup_database': 'डेटाबेस सफाई',
    'database_info': 'डेटाबेस जानकारी',
    'predefined': 'पूर्वनिर्धारित',
    'custom': 'कस्टम',
    'new_pests': 'नए (पिछले 5 दिन)',
    'note': 'नोट',
    'predefined_warning': 'पूर्वनिर्धारित कीट (pest_library.py से) केवल पढ़ने के लिए हैं और संपादित या हटाए नहीं जा सकते। केवल कस्टम कीट (एडमिन पैनल के माध्यम से जोड़े गए) संशोधित किए जा सकते हैं।',
    'search_placeholder': 'नाम, वैज्ञानिक नाम या विवरण से कीट खोजें...',
    'all_severity': 'सभी गंभीरता स्तर',
    'low_severity': 'कम गंभीरता',
    'medium_severity': 'मध्यम गंभीरता',
    'high_severity': 'उच्च गंभीरता',
    'very_high_severity': 'बहुत उच्च गंभीरता',
    'all_types': 'सभी प्रकार',
    'predefined_only': 'केवल पूर्वनिर्धारित',
    'custom_only': 'केवल कस्टम',
    'total_pests': 'कुल कीट',
    'high_severity': 'उच्च गंभीरता',
    'newly_added': 'नव जोड़े गए',
    'custom_pests': 'कस्टम कीट',
    'predefined_pests': 'पूर्वनिर्धारित कीट',
    'effects': 'प्रभाव',
    'solutions': 'समाधान',
    'added': 'जोड़ा गया',
    'detected': 'पता चला',
    'times': 'बार',
    'selected': 'चयनित',
    'no_pests_found': 'कोई कीट नहीं मिला',
    'empty_library': 'कीट लाइब्रेरी वर्तमान में खाली है।',
    'add_first_pest': 'अपना पहला कीट जोड़ें',
    'about_pest_management': 'कीट प्रबंधन के बारे में',
    'identification_tips': 'पहचान युक्तियाँ',
    'prevention_strategies': 'रोकथाम रणनीतियाँ',
    'quick_actions': 'त्वरित कार्य',
    'tip1': 'पत्तियों पर विशिष्ट क्षति पैटर्न देखें',
    'tip2': 'कीट व्यवहार और भोजन समय देखें',
    'tip3': 'अंडे या लार्वा के लिए पत्तियों के नीचे की जाँच करें',
    'tip4': 'छोटे कीटों के लिए आवर्धक कांच का उपयोग करें',
    'tip5': 'मौसमी पैटर्न और मौसम की स्थिति नोट करें',
    'strategy1': 'नियमित रूप से फसल चक्रण का अभ्यास करें',
    'strategy2': 'उचित खेत स्वच्छता बनाए रखें',
    'strategy3': 'प्रतिरोधी फसल किस्मों का उपयोग करें',
    'strategy4': 'जैविक नियंत्रण लागू करें',
    'strategy5': 'खेतों की नियमित निगरानी करें',
    'action1': 'संक्रमित पौधों को तुरंत अलग करें',
    'action2': 'पहले जैविक उपचार लागू करें',
    'action3': 'कीट प्रगति दस्तावेज़ करें',
    'action4': 'गंभीर संक्रमण के लिए विशेषज्ञों से परामर्श लें',
    'action5': 'रसायनों के साथ सुरक्षा प्रोटोकॉल का पालन करें',
    'select_all': 'सभी चुनें (केवल कस्टम कीट)',
    'migrate_confirm': 'यह अपलोड से कीटों को लाइब्रेरी में स्थानांतरित करेगा। जारी रखें?',
    'cleanup_confirm': 'यह कीट डेटाबेस की सफाई करेगा। जारी रखें?',
    'delete_selected': 'चयनित हटाएं',
    'clear_selection': 'चयन साफ़ करें',
    'view': 'देखें',
    'edit': 'संपादित करें',
    'delete': 'हटाएं',
    'view_details': 'विवरण देखें',
    }
}